### ISSUE TITLE
getting Uncaught TypeError: Cannot read property 'width' of undefined JS9 when embedding in Ipython notebook

### ISSUE THREAD

**Issue by gijzelaerr** [ericmandel/js9#10]
We are a bit further in getting the JS9 code into an Ipython notebook, but we run into problems running the following notebook:

https://nbviewer.jupyter.org/gist/bollwyvl/1259dd3bb7cef8988e92

We get an alert with the message 'could not read JS9 data', and in the js console we have:

`Uncaught TypeError: Cannot read property 'width' of undefined (js9.js:1373)`

**Comment by ericmandel** [comment]
I think you are violating the Web's same-origin policy -- you can't load an image from a Web server different from the Web server from which you loaded the JavaScript that processes the image. You need special techniques for that. JS9 implements a proxy load capabilityt, you need a server that can do the proxy load -- we don't have that (yet) in the Jupyter implementation.

So for right now, don't try to do JS9.Load of a remote file. Just try to drag and drop and see if that works. We'll deal with same-origin specially after that.

I'd try drag and drop myself, but I don't exactly know what to do! Where is the JS9 page in Jupyter?

**Comment by ericmandel** [comment]
You have:

            js9: "//js9.si.edu/js9/js9",
            js9support: "//js9.si.edu/js9/js9support.min",
            js9plugins: "//js9.si.edu/js9/js9plugins"

Is this the order in which these files will be loaded? If so, js9support has to come before js9.

**Comment by gijzelaerr** [comment]
I think the `shim` section defines a dependency graph which will determine the loading order.

I think `js9support` is loaded, then `js9plugins` followed by `js9`.

Did you try loading the Jupyter notebook yourself, or are you using the online version? The online version is not working properly, you need to load the notebook inside a running Jupyter notebook.

**Comment by gijzelaerr** [comment]
it looks like I can drag and drop an image onto JS9 running inside the nodebook, but the menu's don't seem to work.

![screen shot 2015-11-24 at 11 45 25](https://cloud.githubusercontent.com/assets/326308/11363200/f6b19782-92a0-11e5-9e38-29464c1e7024.png)

**Comment by ericmandel** [comment]
> I think js9support is loaded, then js9plugins followed by js9.

js9plugins should be loaded after js9, not before.

>  it looks like I can drag and drop an image onto JS9 running inside the nodebook, but the menu's don't seem to work.

It doesn't look like the CSS was loaded properly. The menu buttons are too close together. If the menu buttons do not work, I suspect there will be an error in the javascript console window. When you're in the Jupyter notebook, can you bring up the javascript console window and look at the JS9 warnings and error messages? That should tell us a lot of info about what is going on.

> Did you try loading the Jupyter notebook yourself, or are you using the online version? The online version is not working properly, you need to load the notebook inside a running Jupyter notebook.

I've been given instructions about how to get Jupyter running but have not had time to do it yet ...

**Comment by gijzelaerr** [comment]
running an jupyter notebook is not hard, if you have `pip` available on your system, you can just run `pip install notebook`, which should install everything you need. If you then do `jupyter notebook`, you will be serving the notebooks from your current working folder, which you can access from your browser pointing to localhost. You need to download the notebook i created or, recreate it with the code snippets. 

When dropping the iage inside the window nothing pops up in the console, also not when I press buttons. attached you find a screenshot of the console.

![screen shot 2015-11-24 at 13 31 42](https://cloud.githubusercontent.com/assets/326308/11365574/0cfdb4da-92b0-11e5-8902-3e19fcbf7acd.png)

**Comment by gijzelaerr** [comment]
I suddenly see these 404 errors now, I don't understand why I have missed those before... investigating.

**Comment by ericmandel** [comment]
Knowing next to nothing, I installed miniconda and set up a js9/notebook environment and then ran
````
jupyter notebook
````
eventually getting the output below. Can you see what is wrong? I'm close to being able to help ...

<img width="1200" alt="screen shot 2015-11-24 at 7 13 42 pm" src="https://cloud.githubusercontent.com/assets/3028875/11384697/eec29280-92df-11e5-974a-2a5ae0a11bc8.png">

**Comment by gijzelaerr** [comment]
Hi @ericmandel , forget about the js9notebook for now, you can just directly copy paste the following content in a cell:

```
%%html
<div class="JS9Menubar"></div>
<div class="JS9" id="JS9"></div>
<link type="text/css" rel="stylesheet" href="//js9.si.edu/js9/js9support.css">
<link type="text/css" rel="stylesheet" href="//js9.si.edu/js9/css/tabcontent.css">
<link type="text/css" rel="stylesheet" href="//js9.si.edu/js9/js9.css">
<script type="text/javascript" src="//js9.si.edu/js9/js9support.js"></script>
<script type="text/javascript" src="//js9.si.edu/js9/js9.js"></script>
<script type="text/javascript" src="//js9.si.edu/js9/js9plugins.js"></script>
```

Note that Nicholas Bollweg used the requireJS method, I think to get arround the javacsript eval() issue that doesn't include access to the global variables. You can also try to copy paste the content of these cells:

https://nbviewer.jupyter.org/gist/bollwyvl/1259dd3bb7cef8988e92

**Comment by ericmandel** [comment]
Something is wrong. I loaded local copies of js9 into a jupyter notebook:
````
%%html
<div class="JS9Menubar"></div>
<div class="JS9"></div>
<link type="text/css" rel="stylesheet" href="http://localhost/~eric/js9/js9support.css">
<link type="text/css" rel="stylesheet" href="http://localhost/~eric/js9/js9.css">
<script type="text/javascript" src="http://localhost/~eric/js9/js9support.js"></script>
<script type="text/javascript" src="http://localhost/~eric/js9/js9.js"></script>
<script type="text/javascript" src="http://localhost/~eric/js9/js9plugins.js"></script>
````
and I got the errors in the javascript console window below. A few things to note:

> ReferenceError: fabric is not defined

This indicates that fabric.js is not defined in js9.js, which probably means that js9support.js was not loaded when js9.js was compiled.

> TypeError: JS9.RegisterPlugin is not a function

This is probably happening in js9plugins.js and would indicate that js9.js was not loaded at the time -- which could be because of the error in js9.js above ... so perhaps not a big deal.

> Successfully compiled asm.js code (loaded from cache in 15ms)

Important: this is the last line of the Web console output, but it should be above the load of js9.js, because it's part of js9support.js. So the question is: is js9support.js getting loaded asynchronously, so that it finishes loading after trying to load js9.js? Can that be made synchronous?

<img width="1201" alt="screen shot 2015-11-25 at 11 44 53 am" src="https://cloud.githubusercontent.com/assets/3028875/11403309/20e78592-936a-11e5-8a97-939fe8ec0fbb.png">

**Comment by gijzelaerr** [comment]
Short answer from mobile. It had to do with that eval() can't access the
global scope.
Op 25 nov. 2015 6:50 p.m. schreef "Eric Mandel" <notifications@github.com>:

**Comment by ericmandel** [comment]
Ah, so that means we need to use js9-allinone. And in fact, that works pretty well:

%%html
<div class="JS9Menubar"></div>
<div class="JS9"></div>
<link type="text/css" rel="stylesheet" href="http://js9.si.edu/js9/js9-allinone.css">
<script type="text/javascript" src="http://js9.si.edu/js9/js9-allinone.js"></script>

<img width="903" alt="screen shot 2015-11-25 at 12 23 08 pm" src="https://cloud.githubusercontent.com/assets/3028875/11404343/62ff7a20-936f-11e5-8e66-ddacdd44ea47.png">

**Comment by ericmandel** [comment]
Fixed the aesthetic problem with the menus (see dark area behind menu buttons, above). It now looks like it should ... and behaves as it should too ... except for the fact that the light windows are relative to the whole web page, not the smaller display containing js9.

**Comment by gijzelaerr** [comment]
Great you got it to work! But... It still doesn't work for me. What browser are you using? I tried this with Chrome, Safari and Firefox but all give the same error.

```
%%html
<div class="JS9Menubar"></div>
<div class="JS9" id="JS9"></div>
<link type="text/css" rel="stylesheet" href="//js9.si.edu/js9/js9-allinone.css">
<script type="text/javascript" src="//js9.si.edu/js9/js9-allinone.js"></script>
```
![screen shot 2015-11-26 at 10 07 35](https://cloud.githubusercontent.com/assets/326308/11418821/0e273886-942c-11e5-89bc-f1c9b2a72ae5.png)
![screen shot 2015-11-26 at 10 07 52](https://cloud.githubusercontent.com/assets/326308/11418822/0e2774fe-942c-11e5-9d1a-bf6b43441196.png)
![screen shot 2015-11-26 at 10 53 50](https://cloud.githubusercontent.com/assets/326308/11418820/0e25e7ba-942c-11e5-91e7-3528e7b8a79d.png)

**Comment by ericmandel** [comment]
I have the scheme included, whereas you not specifying the scheme. Try:
````
%%html
<div class="JS9Menubar"></div>
<div class="JS9"></div>
<link type="text/css" rel="stylesheet" href="http://js9.si.edu/js9/js9-allinone.css">
<script type="text/javascript" src="http://js9.si.edu/js9/js9-allinone.js"></script>
````
(I'm using FF at the moment.)

**Comment by gijzelaerr** [comment]
did you change something in the online javascript code? It suddenly is working for me for all browsers!

**Comment by ericmandel** [comment]
I've made a ton of changes over the past week (mostly: added JS9.ResizeDisplay capability) but only one minor change related to this project (removed old and unused jquery-ui class from the menu button definition) ...

**Comment by gijzelaerr** [comment]
no i mean in the last half hour. I don't understand, suddenly it works.

That is a bit the problem with using code from an online web service, you are never sure which version you are using.

**Comment by ericmandel** [comment]
No, it's 5am here and I just woke up!

I agree that on-line URLs can be an issue. Should they be the most current one or should they be stable? Actually, I don't know how you "release" a Jupyter notebook. Will those 5 lines of code be "packaged" somewhere so that users can find and load it automatically, or do they just copy and paste?

**Comment by gijzelaerr** [comment]
What you could do is put releases in a separate directory named after the version on the webserver, that way people can decide which version they use and it won't break. We can also upload js9 to a CDN.

About the notebook, i'm not sure yet! First problem was to get the thing working, which is sort of does now. I first want to find out why it wasn't working properly before for me.

**Comment by ericmandel** [comment]
Yes, that's a good idea. We also can offer different configurations with different JS9 elements: basic (display + menu), panzoom, imexam, etc. But I agree that first it has to work flawlessly.

Some other things to think about:

1. if you execute the cell twice, it gives an error.
2. why does it not do the ajax call correctly to get the socket.io code? It would be a bonus if users had access to the back-end helper.

Anyway, it's Thanksgiving in the US, so I'll be away from my screen ...

**Comment by gijzelaerr** [comment]
1> Yes. I think maybe it is good to split the loading of js9 and
initialisation of the div element. This gives more control during
interactive javascript usage.

2> I have no idea.

Enjoy thanksgiving!

2015-11-26 15:07 GMT+02:00 Eric Mandel <notifications@github.com>:

> Yes, that's a good idea. We also can offer different configurations with
> different JS9 elements: basic (display + menu), panzoom, imexam, etc. But I
> agree that first it has to work flawlessly.
>
> Some other things to think about:
>
>    1. if you execute the cell twice, it gives an error.
>    2. why does it not do the ajax call correctly to get the socket.io
>    code? It would be a bonus if users had access to the back-end helper.
>
> Anyway, it's Thanksgiving in the US, so I'll be away from my screen ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericmandel/js9/issues/10#issuecomment-159908100>.
>



-- 
Gijs Molenaar
http://pythonic.nl

**Comment by ericmandel** [comment]
> did you change something in the online javascript code? It suddenly is working for me for all browsers!

Oh right ... one thing I did on Wednesday evening was to make the default helper type "none" instead of "nodejs", so that no attempt is made to connect to the back-end helper.

**Comment by ericmandel** [comment]
@gijzelaerr Do you still have interest in this project, or should I close the issue? I can't take this any further myself.

**Comment by gijzelaerr** [comment]
hi @ericmandel, sorry for not spending time on this anymore. Do you mean js9 itself or js9 integration with jupyter notebooks?

I think js9 integration in jupyter can be very useful for us. I hope to be able to spend time on this somewhere this year, but for now i'm too busy with other things. Sorry, I wish I just had more time.

**Comment by ericmandel** [comment]
@gijzelaerr I meant integration with jupyter  ... I can take js9 itself further :) ...  anyway, it's not a problem to leave the issue open, I was just cleaning up some other issues and wondered about the status.

**Comment by gijzelaerr** [comment]
great, it would be a great loss if js9 would lose you as a maintainer ;)

**Comment by ericmandel** [comment]
No, I'm in it for the long haul ... we have a semi-infinite number of things we want to do with JS9 (just pushed multi-extension and 3D cube support to GitHub). But I definitely could use help with the Python connection ... at some point ...

**Comment by gijzelaerr** [comment]
ok so hopefully at some point we can pick this up this year!

**Comment by ericmandel** [comment]
I'm going to close this issue for lack of activity. If anyone is still interested in a js9/Jupyter connections, please have a look at https://github.com/mgckind/jjs9 ...
